source "https://rubygems.org"

gem "jekyll-assets", ">= 3.0.12"
gem "jekyll", ">= 3.9.0"
gem "html-proofer", ">= 3.15.3"
gem "kramdown-parser-gfm"

gem "sprockets", "~> 3.7"
gem "nokogiri", ">= 1.10.8"
gem "kramdown", ">= 2.3.0"
